CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS schema_migrations (name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE festivals (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, name_bn text NOT NULL,
 venue text NOT NULL, address text NOT NULL, status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PUBLISHED','PAUSED','CLOSED')),
 hold_minutes int NOT NULL DEFAULT 10 CHECK(hold_minutes BETWEEN 1 AND 30), max_quantity int NOT NULL DEFAULT 6 CHECK(max_quantity BETWEEN 1 AND 20),
 entry_before int NOT NULL DEFAULT 60 CHECK(entry_before>=0), entry_after int NOT NULL DEFAULT 15 CHECK(entry_after>=0),
 physical_required boolean NOT NULL DEFAULT false, contact_email text NOT NULL, terms text NOT NULL,
 capacity_approved boolean NOT NULL DEFAULT false, policies_approved boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contact text NOT NULL UNIQUE, name text NOT NULL DEFAULT '', role text NOT NULL DEFAULT 'customer' CHECK(role IN ('customer','owner','inventory','finance','desk','scanner','supervisor')), mfa_secret text, verified_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE otp_challenges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contact text NOT NULL, digest text NOT NULL, expires_at timestamptz NOT NULL, attempts int NOT NULL DEFAULT 0, used boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX otp_contact_time ON otp_challenges(contact,created_at DESC);
CREATE TABLE sessions (digest text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE rate_limits (key text PRIMARY KEY, count int NOT NULL, reset_at timestamptz NOT NULL);
CREATE TABLE shows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_id uuid NOT NULL REFERENCES festivals(id), title text NOT NULL, title_bn text NOT NULL, troupe text NOT NULL, synopsis text NOT NULL, synopsis_bn text NOT NULL, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, language text NOT NULL DEFAULT 'Bengali', runtime int NOT NULL CHECK(runtime>0), genre text NOT NULL, artwork text NOT NULL DEFAULT 'red', status text NOT NULL DEFAULT 'PUBLISHED' CHECK(status IN ('DRAFT','PUBLISHED','CANCELLED')), CHECK(ends_at>starts_at));
CREATE TABLE capacities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), show_id uuid NOT NULL REFERENCES shows(id), zone text NOT NULL CHECK(zone IN ('Premier','Superior','Balcony')), ceiling int NOT NULL CHECK(ceiling>=0), version int NOT NULL DEFAULT 1, row_count int NOT NULL DEFAULT 12 CHECK(row_count>0), UNIQUE(show_id,zone));
CREATE TABLE pools (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), capacity_id uuid NOT NULL REFERENCES capacities(id), kind text NOT NULL CHECK(kind IN ('DAILY','SEASON')), allocation int NOT NULL CHECK(allocation>=0), held int NOT NULL DEFAULT 0 CHECK(held>=0), committed int NOT NULL DEFAULT 0 CHECK(committed>=0), row_start int NOT NULL CHECK(row_start>0), row_end int NOT NULL CHECK(row_end>=row_start), version int NOT NULL DEFAULT 1, UNIQUE(capacity_id,kind), CHECK(held+committed<=allocation));
CREATE TABLE products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_id uuid NOT NULL REFERENCES festivals(id), name text NOT NULL, name_bn text NOT NULL, category text NOT NULL CHECK(category IN ('Premier','Superior','Balcony')), kind text NOT NULL CHECK(kind IN ('DAILY','SEASON')), price int NOT NULL CHECK(price>=0), version int NOT NULL DEFAULT 1, enabled boolean NOT NULL DEFAULT true, cap int CHECK(cap>=0), show_id uuid REFERENCES shows(id));
CREATE TABLE product_coverage (product_id uuid NOT NULL REFERENCES products(id), show_id uuid NOT NULL REFERENCES shows(id), pool_id uuid NOT NULL REFERENCES pools(id), weight int NOT NULL DEFAULT 1 CHECK(weight>0), PRIMARY KEY(product_id,show_id));
CREATE TABLE bookings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reference text NOT NULL UNIQUE, user_id uuid NOT NULL REFERENCES users(id), product_id uuid NOT NULL REFERENCES products(id), quantity int NOT NULL CHECK(quantity>0), unit_price int NOT NULL CHECK(unit_price>=0), fees int NOT NULL DEFAULT 0 CHECK(fees>=0), tax int NOT NULL DEFAULT 0 CHECK(tax>=0), total int NOT NULL CHECK(total>=0), currency text NOT NULL DEFAULT 'INR' CHECK(currency='INR'), product_version int NOT NULL, snapshot jsonb NOT NULL, status text NOT NULL CHECK(status IN ('HELD','PAYMENT_PENDING','CONFIRMED','EXPIRED','REFUND_REQUIRED','CANCELLED')), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX bookings_owner ON bookings(user_id,created_at DESC);
CREATE INDEX bookings_expiry ON bookings(expires_at) WHERE status IN ('HELD','PAYMENT_PENDING');
CREATE TABLE hold_allocations (booking_id uuid NOT NULL REFERENCES bookings(id), pool_id uuid NOT NULL REFERENCES pools(id), quantity int NOT NULL CHECK(quantity>0), state text NOT NULL CHECK(state IN ('HELD','COMMITTED','RELEASED')), PRIMARY KEY(booking_id,pool_id));
CREATE TABLE payment_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), booking_id uuid NOT NULL REFERENCES bookings(id), provider_order_id text UNIQUE, state text NOT NULL DEFAULT 'CREATING' CHECK(state IN ('CREATING','READY','UNCERTAIN','FAILED')), created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX payment_open_attempt ON payment_attempts(booking_id) WHERE state IN ('CREATING','READY','UNCERTAIN');
CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), booking_id uuid NOT NULL REFERENCES bookings(id), provider_payment_id text NOT NULL UNIQUE, provider_order_id text NOT NULL, amount int NOT NULL CHECK(amount>0), currency text NOT NULL CHECK(currency='INR'), state text NOT NULL CHECK(state IN ('AUTHORIZED','CAPTURED','FAILED')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), booking_id uuid NOT NULL REFERENCES bookings(id), ordinal int NOT NULL CHECK(ordinal>0), reference text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','CANCELLED','SUSPENDED')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(booking_id,ordinal));
CREATE TABLE entitlements (ticket_id uuid NOT NULL REFERENCES tickets(id), show_id uuid NOT NULL REFERENCES shows(id), pool_id uuid NOT NULL REFERENCES pools(id), status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','CANCELLED','SUSPENDED')), weight int NOT NULL DEFAULT 1 CHECK(weight>0), PRIMARY KEY(ticket_id,show_id));
CREATE TABLE credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES tickets(id), digest text NOT NULL UNIQUE, encrypted_token text NOT NULL, kind text NOT NULL CHECK(kind IN ('DIGITAL','PHYSICAL')), status text NOT NULL CHECK(status IN ('PREPARED','ACTIVE','REVOKED')), created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX one_active_credential ON credentials(ticket_id) WHERE status='ACTIVE';
CREATE TABLE physical_issues (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES tickets(id), credential_id uuid NOT NULL REFERENCES credentials(id), serial text NOT NULL UNIQUE, state text NOT NULL DEFAULT 'PREPARED' CHECK(state IN ('PREPARED','ISSUED','VOID')), evidence text NOT NULL, actor_id uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), issued_at timestamptz);
CREATE UNIQUE INDEX one_prepared_issue ON physical_issues(ticket_id) WHERE state='PREPARED';
CREATE TABLE devices (id text PRIMARY KEY, name text NOT NULL, revoked boolean NOT NULL DEFAULT false);
CREATE TABLE staff_scopes (user_id uuid NOT NULL REFERENCES users(id), show_id uuid NOT NULL REFERENCES shows(id), gate text NOT NULL, device_id text NOT NULL REFERENCES devices(id), PRIMARY KEY(user_id,show_id,gate,device_id));
CREATE TABLE scan_requests (id uuid PRIMARY KEY, actor_id uuid NOT NULL REFERENCES users(id), input_digest text NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE admissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL, show_id uuid NOT NULL, request_id uuid NOT NULL UNIQUE, gate text NOT NULL, device_id text NOT NULL, actor_id uuid NOT NULL REFERENCES users(id), admitted_at timestamptz NOT NULL DEFAULT now(), UNIQUE(ticket_id,show_id), FOREIGN KEY(ticket_id,show_id) REFERENCES entitlements(ticket_id,show_id));
CREATE INDEX admissions_show ON admissions(show_id,admitted_at);
CREATE TABLE refunds (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), booking_id uuid NOT NULL REFERENCES bookings(id), payment_id uuid NOT NULL REFERENCES payments(id), amount int NOT NULL CHECK(amount>0), state text NOT NULL DEFAULT 'REQUESTED' CHECK(state IN ('REQUESTED','PROCESSING','SUCCEEDED','FAILED')), reason text NOT NULL, provider_refund_id text UNIQUE, rights jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency (scope text NOT NULL, key text NOT NULL, input_digest text NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(scope,key));
CREATE TABLE movements (id bigserial PRIMARY KEY, pool_id uuid NOT NULL REFERENCES pools(id), operation text NOT NULL, delta_held int NOT NULL DEFAULT 0, delta_committed int NOT NULL DEFAULT 0, delta_allocation int NOT NULL DEFAULT 0, reason text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX movements_pool ON movements(pool_id,id);
CREATE TABLE audit_events (id bigserial PRIMARY KEY, actor_id uuid REFERENCES users(id), action text NOT NULL, entity text NOT NULL, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE webhook_events (id text PRIMARY KEY, payload jsonb NOT NULL, digest text NOT NULL, processed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kind text NOT NULL, key text NOT NULL UNIQUE, payload jsonb NOT NULL, state text NOT NULL DEFAULT 'PENDING' CHECK(state IN ('PENDING','RUNNING','DONE','FAILED')), attempts int NOT NULL DEFAULT 0, run_at timestamptz NOT NULL DEFAULT now(), locked_at timestamptz, last_error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX jobs_ready ON jobs(run_at) WHERE state IN ('PENDING','RUNNING');
CREATE TABLE reconciliation_cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL UNIQUE, kind text NOT NULL, detail jsonb NOT NULL, state text NOT NULL DEFAULT 'OPEN', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE legal_holds (user_id uuid PRIMARY KEY REFERENCES users(id), reason text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE deletion_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, action text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION protect_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only record'; END $$;
CREATE TRIGGER immutable_movements BEFORE UPDATE OR DELETE ON movements FOR EACH ROW EXECUTE FUNCTION protect_append_only();
CREATE TRIGGER immutable_audit BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION protect_append_only();
